### ISSUE TITLE
Design registration 

### ISSUE THREAD

**Issue by baxterrp** [baxterrp/kcb-blackjack#1]
Come up with a plan for the registration page. 

-appearance(bootstrap or custom)
-required fields(what data we need about our users)
-front end validation 
-create post to /register end point with user data(does not have to function until next issue)

**Comment by baxterrp** [comment]
consider for registration page 
-email
-first name
-last name
-birth date (for validating age requirements)
-password

lets not stress about login page until design for this is complete. We will need a task for that. Validation is also only in design phase, don't worry about building it yet.

**Comment by MrRiceGuy** [comment]
So I'm making the calendar for a DOB selection and I ran into examples that use tables and none that use divs. I don't mind using tables at all, but is there an actual reason? Are they simpler to process or something?

**Comment by baxterrp** [comment]
Please only use tables for tabular data. As far as I am concerned the examples are wrong. Try to make it work with a div.
